### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by maziarzamani** [alikian/CC3200MOD#1]
Awesome breakout board, but do you by any chance have a BOM? :-) Cheers.

**Comment by alikian** [comment]
I will make one

**Comment by maziarzamani** [comment]
Sounds great :+1:

**Comment by alikian** [comment]
I added bom file but is not complete yet

**Comment by maziarzamani** [comment]
Thanks a lot i appreciate your effort!

**Comment by alikian** [comment]
Completed Bom file, np

**Comment by Mbolland** [comment]
Any chance you ll make a BOM for the Webee CC3200? :o)
